services:

  mysqldb:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - db_mysql_data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: payment_service_db
    healthcheck:
      test: ["CMD" , "mysqladmin" ,"ping", "-h","localhost" ,"-u","root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 20s
      retries: 4

  dbadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: db

volumes:
  db-data_mysql:
