spring:
  application:
    name: pagamentos

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:payment_service_db}?createDatabaseIfNotExist=true
    username: ${DB_USER:root}
    password: ${DB_USER:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration